Monitoring 1
Otus-DevOps-2017-11/avorobyev_microservices pull request #7
Opened 2018-04-26 08:57 UTC by a-vorobyev

ДЗ 21. Готово. Установил, посмотрел.

В документации нашел две заумнейших ссылки:
 https://en.wikipedia.org/wiki/Time_series
 https://en.wikipedia.org/wiki/Unit_of_observation#Data_point

Пытался осознать их три раза, но не осилил, академический стиль решает  :)

2018-04-28 16:07 UTC, Nklya commented
У тебя часть коммитов идет с неправильно настроенного гита. Проверь настройки.
<img width="430" alt="image" src="https://user-images.githubusercontent.com/26086394/39398492-4cf07c36-4b17-11e8-93b7-64b3c9af3cc4.png">

2018-04-28 16:11 UTC, a-vorobyev commented
настройки, да, съехали на 17-м дз, исправил уже

2018-04-28 16:19 UTC, Nklya requested changes
Добрый день.

Александр, добавь пожалуйста в ридми и описание PR ссылку на докер хаб.
И образ прометеуса также должен быть выгружен и он же должен использоваться в докер композе.

2018-04-28 16:19 UTC, Nklya commented on docker/docker-compose.yml
> +    image: prometheus-custom
В таком видео образ прометеуса будет доступен только на локальной машине.
В ДЗ подразумевалась выгрузка образа прометеуса на докер хаб, как и остальных образов.
Т.е. перед его именем должно быть ${USER_NAME}/

2018-04-28 16:23 UTC, a-vorobyev commented on docker/docker-compose.yml
> +    image: prometheus-custom
Николай, я решил не парить себя с докер хабом. Извиняюсь за самоуправство, но я не понял смысла это действа и исключил его из работы. Если понадобится- запушу. Здесь смысла не вижу.

2018-04-28 16:29 UTC, Nklya commented on docker/docker-compose.yml
> +    image: prometheus-custom
Смысл состоит в том, чтобы не билдить каждый раз образ до его использования.
Использование докера без хранилища артефактов (registry, докер хаб) имеет мало смысла.

Во-вторых, присутсвие образов на докер хабе показывает, что ДЗ было действительно выполнено и его можно проверить самостоятельно.

Так что, если тебя не затруднит, запушь образы пожалуйста.

2018-04-28 16:31 UTC, a-vorobyev commented on docker/docker-compose.yml
> +    image: prometheus-custom
Убедил, доделаю

2018-05-03 15:19 UTC, Nklya approved these changes
Добрый день.

Теперь условия ДЗ выполнены, все ок 👍

2018-05-04 12:18 UTC, merged